### ISSUE TITLE
开放平台官网BUG

### ISSUE THREAD

**Issue by ileler** [aqara/opencloud-docs#1]
![test](https://user-images.githubusercontent.com/3371163/34718554-094daf62-f572-11e7-9ca8-201c66376649.gif)

如图，按照你们给的说明“**双击查看完整令牌，刷新后无法恢复，请谨慎操作。**”双击输入框，结果弹了两次密码框，都输入后，`key`出来了，但是准备`copy`时，又隐藏了，体验很不友好。保证安全的同时不要丢了体验。毕竟这个`key`，咱自己（开发者）还是需要`copy`到的嘛。
**双击输入交互不好，和大多数人的高频操作（双击选中文本，复制）冲突了**

**Comment by forrestfung** [comment]
谢谢你的反馈，我会尽快修复这个问题
