### ISSUE TITLE
这个文档里的局域网协议是2.x的，现在的网关协议是1.x的？

### ISSUE THREAD

**Issue by Kagami-src** [aqara/opencloud-docs#2]
这个文档里的局域网协议好像不适用于现在的网关。
以后网关设备升级局域网协议会变成新的2.0协议吗？还是说只有之后出的新网关会是2.0的协议？

**Comment by ileler** [comment]
@Kagami-src 除了原来的米家网关（采用1.x版本的绿米局域网协议），其他的空调伴侣或者后续的新网关，使用的绿米局域网协议是2.x版本

**Comment by Kagami-src** [comment]
@ileler  那米家现在在售的网关 将来会升级2.x协议吗？

**Comment by forrestfung** [comment]
米家在售的网关不会升级到2.x协议的，只有新发布的网关会采用2.x协议
